// Generated by CoffeeScript 1.10.0
(function() {
  var Repo, assert, neo4j, should, sinon;

  should = require('should');

  assert = require('assert');

  sinon = require('sinon');

  neo4j = require('neo4j-driver').v1;

  Repo = require('../src/repositories/Neo4jRepository');

  describe('Build Simple Graph', function() {
    var spy;
    spy = null;
    before(function(done) {
      var repo;
      sinon.stub(neo4j, "driver");
      neo4j.driver = sinon.stub().returns(42);
      repo = new Repo({
        url: "bolt://user:pass@localhost"
      });
      done();
    });
    it('constructs', function(done) {
      repo.config.url.should.be.equal("bolt://localhost");
      repo.config.user.should.be.equal("user");
      repo.config.pass.should.be.equal("pass");
      assert(neo4j.driver.called);
      repo.neo4j.should.not.be["null"];
      return done();
    });
    return it('gets', function(done) {});
  });

}).call(this);

//# sourceMappingURL=test_neo4jrepository.js.map
