// Generated by CoffeeScript 1.10.0
(function() {
  var Builder, Papa, async, fs, geodist, iImport, math, papaConfig,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  iImport = require('./../iImport');

  fs = require('fs');

  async = require('async');

  math = require('mathjs');

  geodist = require('geodist');

  fs = require('fs');

  Papa = require('babyparse');

  papaConfig = {
    delimiter: ",",
    newline: "",
    header: true,
    dynamicTyping: false,
    preview: 0,
    encoding: "UTF-8",
    worker: false,
    comments: false,
    step: void 0,
    download: false,
    skipEmptyLines: false,
    fastMode: false
  };

  Builder = (function(superClass) {
    extend(Builder, superClass);

    function Builder(config, repo1) {
      this.config = config;
      this.repo = repo1 != null ? repo1 : null;
      this.buildZipsToLtls = bind(this.buildZipsToLtls, this);
    }

    Builder.prototype.setRepo = function(repo) {
      return this.repo = repo;
    };

    Builder.prototype.wireupZipsToLtls = function(aix, nodes, ltls, callback) {
      var i, id, len, ltl, obj, params, zip;
      zip = nodes[aix];
      this.repo.pipeline();
      if ((zip != null) && zip.zip3 !== '') {
        for (i = 0, len = ltls.length; i < len; i++) {
          ltl = ltls[i];
          if (zip.id === '') {
            continue;
          }
          id = zip.zip3 + "_" + ltl.ltlCode + "_" + ltl.weightLo + "_" + ltl.weightHi;
          params = {
            sourcekind: 'Zip',
            sourceid: '' + zip.id,
            destinationkind: 'Ltl',
            destinationid: '' + id,
            kind: 'ZIPLTL'
          };
          obj = {
            kind: 'ZIPLTL',
            cost: 0,
            id: zip.id + "_" + id
          };
          this.repo.setEdge(params, obj);
        }
      }
      return this.repo.exec((function(_this) {
        return function(error, result) {
          console.log("nodes: " + nodes.length + " ix: " + aix);
          if ((error != null)) {
            console.log("error:" + result);
            return callback(error, result);
          } else if (aix + 1 < nodes.length) {
            return _this.wireupZipsToLtls(aix + 1, nodes, ltls, callback);
          } else {
            console.log("Finished");
            return callback(error, result);
          }
        };
      })(this));
    };

    Builder.prototype.buildZipsToLtls = function(callback) {
      var filename;
      filename = './data/weights-codes.csv';
      this.repo.find({
        type: "Zip"
      }, (function(_this) {
        return function(error, zips) {
          var contentsCodes, ltls, result;
          contentsCodes = fs.readFileSync(filename, 'utf8');
          result = Papa.parse(contentsCodes, papaConfig);
          ltls = result.data;
          _this.wireupZipsToLtls(0, zips, ltls, callback);
        };
      })(this));
    };

    return Builder;

  })(iImport);

  module.exports = Builder;

}).call(this);

//# sourceMappingURL=ZipsToLtls.js.map
