// Generated by CoffeeScript 1.10.0
(function() {
  var Builder, Papa, async, fs, geodist, iImport, math, papaConfig,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  iImport = require('./iImport');

  fs = require('fs');

  async = require('async');

  math = require('mathjs');

  geodist = require('geodist');

  fs = require('fs');

  Papa = require('babyparse');

  papaConfig = {
    delimiter: ",",
    newline: "",
    header: true,
    dynamicTyping: false,
    preview: 0,
    encoding: "UTF-8",
    worker: false,
    comments: false,
    step: void 0,
    download: false,
    skipEmptyLines: false,
    fastMode: false
  };

  Builder = (function(superClass) {
    extend(Builder, superClass);

    function Builder(config, repo1) {
      this.config = config;
      this.repo = repo1 != null ? repo1 : null;
      this.build = bind(this.build, this);
      this.buildSkusToWarehouses = bind(this.buildSkusToWarehouses, this);
      this.buildWarehousesToZips = bind(this.buildWarehousesToZips, this);
      this.buildResuppliers = bind(this.buildResuppliers, this);
      this.buildSweeps = bind(this.buildSweeps, this);
      this.buildLtlToLtl = bind(this.buildLtlToLtl, this);
      this.traverseZips = bind(this.traverseZips, this);
      this.wireupLtlsToLtls = bind(this.wireupLtlsToLtls, this);
      this.buildZipsToLtls = bind(this.buildZipsToLtls, this);
    }

    Builder.prototype.setRepo = function(repo) {
      return this.repo = repo;
    };

    Builder.prototype.wireupZipsToLtls = function(aix, nodes, ltls, callback) {
      var i, id, len, ltl, obj, params, zip;
      zip = nodes[aix];
      this.repo.pipeline();
      if ((zip != null) && zip.zip3 !== '') {
        for (i = 0, len = ltls.length; i < len; i++) {
          ltl = ltls[i];
          if (zip.id === '') {
            continue;
          }
          id = zip.zip3 + "_" + ltl.ltlCode + "_" + ltl.weightLo + "_" + ltl.weightHi;
          params = {
            sourcekind: 'Zip',
            sourceid: '' + zip.id,
            destinationkind: 'LtlCode',
            destinationid: '' + id,
            kind: 'ZIPLTL'
          };
          obj = {
            kind: 'ZIPLTL',
            cost: 0,
            id: zip.id + "_" + id
          };
          this.repo.setEdge(params, obj);
        }
      }
      return this.repo.exec((function(_this) {
        return function(error, result) {
          console.log("nodes: " + nodes.length + " ix: " + aix);
          if ((error != null)) {
            console.log("error:" + result);
            return callback(error, result);
          } else if (aix + 1 < nodes.length) {
            return _this.wireupZipsToLtls(aix + 1, nodes, ltls, callback);
          } else {
            console.log("Finished");
            return callback(error, result);
          }
        };
      })(this));
    };

    Builder.prototype.buildZipsToLtls = function(callback) {
      var filename;
      filename = './data/weights-codes.csv';
      this.repo.find({
        type: "Zip"
      }, (function(_this) {
        return function(error, zips) {
          var contentsCodes, ltls, result;
          contentsCodes = fs.readFileSync(filename, 'utf8');
          result = Papa.parse(contentsCodes, papaConfig);
          ltls = result.data;
          _this.wireupZipsToLtls(0, zips, ltls, callback);
        };
      })(this));
    };

    Builder.prototype.wireupLtlsToLtls = function(aix, bix, zips, ltls, callback) {
      var distance, i, id1, id2, len, ltl, obj, params, zip1, zip2;
      zip1 = zips[aix];
      zip2 = zips[bix];
      this.repo.pipeline();
      if (zip1.zip3 !== '' && zip2 !== '') {
        for (i = 0, len = ltls.length; i < len; i++) {
          ltl = ltls[i];
          distance = geodist({
            lat: parseInt(zip1.latitude),
            lon: parseInt(zip1.longitude)
          }, {
            lat: parseInt(zip2.latitude),
            lon: parseInt(zip2.longitude)
          });
          id1 = zip1.zip3 + "_" + ltl.ltlCode + "_" + ltl.weightLo + "_" + ltl.weightHi;
          id2 = zip2.zip3 + "_" + ltl.ltlCode + "_" + ltl.weightLo + "_" + ltl.weightHi;
          params = {
            sourcekind: 'LtlCode',
            sourceid: '' + id1,
            destinationkind: 'LtlCode',
            destinationid: '' + id2,
            kind: 'LTL',
            cost: distance + 10,
            linkid: id1 + '_' + id2
          };
          obj = {
            kind: 'LTL',
            cost: distance + 2,
            id: id1 + "_" + id2
          };
          this.repo.setEdge(params, obj);
        }
      }
      return this.repo.exec((function(_this) {
        return function(error, result) {
          if ((error != null)) {
            console.log("error:" + result);
            return callback(error, result);
          } else if (bix + 1 < zips.length) {
            return _this.wireupLtlsToLtls(aix, bix + 1, zips, ltls, callback);
          } else if (aix + 1 < zips.length) {
            console.log("zip: " + zips[aix].zip3);
            return _this.traverseZips(aix + 1, 0, zips, ltls, callback);
          } else {
            return callback(error, result);
          }
        };
      })(this));
    };

    Builder.prototype.traverseZips = function(aix, bix, zips, ltls, callback) {
      return this.wireupLtlsToLtls(aix, bix, zips, ltls, callback);
    };

    Builder.prototype.buildLtlToLtl = function(callback) {
      var filename;
      filename = './data/weights-codes.csv';
      this.repo.find({
        type: "Zip"
      }, (function(_this) {
        return function(error, zips) {
          var contentsCodes, ltls, result;
          contentsCodes = fs.readFileSync(filename, 'utf8');
          result = Papa.parse(contentsCodes, papaConfig);
          ltls = result.data;
          _this.traverseZips(0, 0, zips, ltls, callback);
        };
      })(this));
    };

    Builder.prototype.buildSweeps = function(callback) {
      return callback(null, true);
    };

    Builder.prototype.buildResuppliers = function(callback) {
      return callback(null, true);
    };

    Builder.prototype.buildWarehousesToZips = function(callback) {
      return callback(null, true);
    };

    Builder.prototype.buildSkusToWarehouses = function(callback) {
      return callback(null, true);
    };

    Builder.prototype.build = function(callback) {
      async.parallel([
        (function(_this) {
          return function(callback) {
            return _this.buildZipsToLtlCodes(callback);
          };
        })(this), (function(_this) {
          return function(callback) {
            return _this.buildLtlCodesToLtlCodes(callback);
          };
        })(this), (function(_this) {
          return function(callback) {
            return _this.buildSweeps(callback);
          };
        })(this), (function(_this) {
          return function(callback) {
            return _this.buildResuppliers(callback);
          };
        })(this), (function(_this) {
          return function(callback) {
            return _this.buildWarehousesToZips(callback);
          };
        })(this), (function(_this) {
          return function(callback) {
            return _this.buildSkusToWarehouses(callback);
          };
        })(this)
      ], (function(_this) {
        return function(error, result) {
          return callback(error, result);
        };
      })(this));
    };

    return Builder;

  })(iImport);

  module.exports = Builder;

}).call(this);

//# sourceMappingURL=EdgeBuilder.js.map
