// Generated by CoffeeScript 1.10.0
(function() {
  var Redis, redis;

  Redis = require('ioredis');

  redis = new Redis('redis://127.0.0.1:6379/1');

  redis.flushall();

}).call(this);

//# sourceMappingURL=flushredis.js.map
