// Generated by CoffeeScript 1.10.0
(function() {
  var Papa, Redis, config, contents, data, fs, i, id, len, pipeline, redis, result, warehouse;

  Papa = require('babyparse');

  Redis = require('ioredis');

  redis = new Redis('redis://127.0.0.1:6379/0');

  fs = require('fs');

  contents = fs.readFileSync('../../data/warehouses.csv', 'utf8');

  config = {
    delimiter: ",",
    newline: "",
    header: true,
    dynamicTyping: false,
    preview: 0,
    encoding: "UTF-8",
    worker: false,
    comments: false,
    step: void 0,
    download: false,
    skipEmptyLines: false,
    fastMode: false
  };

  result = Papa.parse(contents, config);

  data = result.data;

  pipeline = redis.pipeline();

  for (i = 0, len = data.length; i < len; i++) {
    warehouse = data[i];
    id = warehouse.ConsolidatedWarehouseID;
    console.log(id);
    pipeline.set(id, JSON.stringify(warehouse));
  }

  pipeline.exec(function(err, results) {
    console.log("Done: ");
    return console.log(JSON.stringify(results));
  });

  return;

}).call(this);

//# sourceMappingURL=importWarehouses.js.map
