// Generated by CoffeeScript 1.10.0
(function() {
  var Builder, builder, config;

  Builder = require('./edges/EdgeBuilder');

  config = {
    delimiter: ",",
    newline: "",
    header: true,
    dynamicTyping: false,
    preview: 0,
    encoding: "UTF-8",
    worker: false,
    comments: false,
    step: void 0,
    download: false,
    skipEmptyLines: false,
    fastMode: false
  };

  builder = new Builder(config);

  module.exports = builder;

}).call(this);

//# sourceMappingURL=buildEdges.js.map
