// Generated by CoffeeScript 1.10.0
(function() {
  var Papa, WarehouseImporter, async, fs, iImport,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  iImport = require('./iImport');

  Papa = require('babyparse');

  fs = require('fs');

  async = require('async');

  WarehouseImporter = (function(superClass) {
    extend(WarehouseImporter, superClass);

    function WarehouseImporter(config) {
      this.config = config;
    }

    WarehouseImporter.prototype.importKeyValue = function(filename, repo, callback) {
      var contents, data, id, j, len, node, result;
      contents = fs.readFileSync(filename, 'utf8');
      result = Papa.parse(contents, this.config);
      data = result.data;
      repo.pipeline();
      for (j = 0, len = data.length; j < len; j++) {
        node = data[j];
        id = node.ConsolidatedWarehouseID;
        node.type = "Warehouse";
        node.id = id;
        repo.set(id, node, function(error, result) {
          if (error != null) {
            callback(error, null);
          }
        });
      }
      repo.exec(callback);
    };

    WarehouseImporter.prototype["import"] = function(filename, repo, callback) {
      var addFuncs, contents, data, i, j, len, makeAdd, node, result;
      contents = fs.readFileSync(filename, 'utf8');
      result = Papa.parse(contents, this.config);
      data = result.data;
      makeAdd = function(node) {
        return function(callback) {
          return repo.find(JSON.stringify({
            zip: node.zip
          }), function(error, result) {
            if (result.body.length === 0) {
              repo.add(node, function(error, result) {
                if ((error != null)) {
                  console.log(error);
                }
                callback(error, result);
              });
            } else {
              callback(error, result);
            }
          });
        };
      };
      addFuncs = [];
      for (i = j = 0, len = data.length; j < len; i = ++j) {
        node = data[i];
        addFuncs.push(makeAdd(node));
      }
      return async.parallelLimit(addFuncs, 10, function(error, result) {
        if (error != null) {
          console.log(error);
        }
        callback(error, result);
      });
    };

    return WarehouseImporter;

  })(iImport);

  module.exports = WarehouseImporter;

}).call(this);

//# sourceMappingURL=WarehouseImporter.js.map
