// Generated by CoffeeScript 1.10.0
(function() {
  var assert, async, driver, math, neo4j, should;

  should = require('should');

  assert = require('assert');

  math = require('mathjs');

  async = require('async');

  neo4j = require('neo4j-driver').v1;

  driver = neo4j.driver('bolt://localhost', neo4j.auth.basic('neo4j', 'macro7'));

  describe('Delete Graph', function() {
    var deleteGraph;
    deleteGraph = function(done) {
      var session, tx;
      session = driver.session();
      tx = session.beginTransaction();
      console.log("Delete edges");
      tx.run("MATCH ()-[r]->() DELETE r");
      console.log("Delete nodes");
      tx.run("MATCH (n) delete n");
      return tx.commit().subscribe({
        onCompleted: function() {
          console.log("delete completed");
          session.close();
          return done();
        },
        onError: function(error) {
          console.log(error);
          session.close();
          return done();
        }
      });
    };
    return it('deleting graph', function(done) {
      return deleteGraph(function() {
        return done();
      });
    });
  });

}).call(this);

//# sourceMappingURL=delete_graph.js.map
