// Generated by CoffeeScript 1.10.0
(function() {
  var Neo4jRepostitory, Papa, assert, async, fs, importer, should;

  should = require('should');

  assert = require('assert');

  importer = require('../src/importers/importWarehouses');

  async = require('async');

  Neo4jRepostitory = require('../src/repositories/Neo4jRepository');

  fs = require('fs');

  Papa = require('babyparse');

  describe('Import Warehouses', function() {
    var checkAllNodes;
    checkAllNodes = (function(_this) {
      return function(filename, repo, done) {
        var contents, data, getFuncs, i, id, j, len, make, node, result;
        contents = fs.readFileSync(filename, 'utf8');
        result = Papa.parse(contents, _this.config);
        data = result.data;
        make = function(id, type) {
          return function(callback) {
            return repo.get({
              id: id,
              type: type
            }, function(error, result) {
              JSON.parse(result).id.should.be.equal(id);
              callback(null, result);
            });
          };
        };
        getFuncs = [];
        for (i = j = 0, len = data.length; j < len; i = ++j) {
          node = data[i];
          if (i === 0) {
            continue;
          }
          id = node[0];
          getFuncs.push(make(id, 'Warehouse'));
        }
        async.parallelLimit(getFuncs, 1, function(error, results) {
          if (error) {
            console.log('error' + error);
          }
          done();
        });
      };
    })(this);
    return it('Imports Warehouses Neo4j', function(done) {
      var filename, repo, repoConfig;
      repoConfig = {
        user: 'neo4j',
        pass: 'macro7'
      };
      repo = new Neo4jRepostitory(repoConfig);
      filename = './data/warehouses.csv';
      return importer.importKeyValue(filename, repo, function(error, results) {
        if ((error != null)) {
          console.log(error);
          assert(false);
          done();
          return;
        }
        repo.get({
          id: '2000502',
          type: 'Warehouse'
        }, function(error, result) {
          var data;
          if ((error != null)) {
            assert(false);
            done();
            return;
          }
          data = JSON.parse(result);
          data.id.should.be.equal('2000502');
          checkAllNodes(filename, repo, done);
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=test_import_warehouses.js.map
