// Generated by CoffeeScript 1.10.0
(function() {
  var Neo4jRepostitory, assert, async, builder, should;

  should = require('should');

  assert = require('assert');

  async = require('async');

  Neo4jRepostitory = require('../src/repositories/Neo4jRepository');

  builder = require('../src/importers/edges/ZipsToLtls');

  describe('Build Edges', function() {
    return it('Wires Up ZipCodes to LtlCodes.', function(done) {
      var repo, repoConfig;
      repoConfig = {
        user: 'neo4j',
        pass: 'macro7'
      };
      repo = new Neo4jRepostitory(repoConfig);
      builder.setRepo(repo);
      return builder.buildZipsToLtls(function(error, results) {
        if ((error != null)) {
          console.log(error);
          assert(false);
        }
        done();
      });
    });
  });

}).call(this);

//# sourceMappingURL=test_wireup_zips_to_ltl.js.map
