// Generated by CoffeeScript 1.10.0
(function() {
  $CREATE(INDEX({
    ON: LtlCode(id)
  }));

  $CREATE(INDEX({
    ON: Zip(id)
  }));

  $CREATE(INDEX({
    ON: Zip(id)
  }));

  $CREATE(INDEX({
    ON: Zip(id)
  }));

}).call(this);

//# sourceMappingURL=create_indexes.js.map
