// Generated by CoffeeScript 1.10.0
(function() {
  var CodeSchema, Mongoose, Schema;

  Mongoose = require('mongoose');

  Schema = require('mongoose').Schema;

  CodeSchema = new Schema({
    zip: String,
    city: String,
    state: String,
    latitude: String,
    longitude: String,
    timezone: String,
    dst: String
  }, {
    strict: false
  });

  module.exports = {
    model: Mongoose.model("Code", CodeSchema),
    schema: CodeSchema
  };

}).call(this);

//# sourceMappingURL=code.js.map
