// Generated by CoffeeScript 1.10.0
(function() {
  var Mongoose, NodeSchema, ObjectId, Schema;

  Mongoose = require('mongoose');

  Schema = require('mongoose').Schema;

  ObjectId = Mongoose.Schema.Types.ObjectId;

  NodeSchema = new Schema({
    transit: Boolean,
    storage: Boolean,
    leaf: Boolean,
    consolidator: Boolean,
    deconsolidator: Boolean,
    routes: [
      {
        type: ObjectId,
        ref: 'Route'
      }
    ]
  }, {
    strict: false
  });

  module.exports = {
    model: Mongoose.model("Node", NodeSchema),
    schema: NodeSchema
  };

}).call(this);

//# sourceMappingURL=node.js.map
